import matplotlib.pyplot as plt

# Creating a histograme......
values = [0, 10, 20, 100, 150, 200, 300, 400, 500, 600, 800]
plt.hist(values, color="green")
plt.hist(values, bins=4) # Show Data in 3 intervals...
plt.plot(kind="bar") # covert the line graph into bar graph...

plt.show()
plt.savefig("matplot.jpeg") # Save The graph in file....
