# Importing Modules......
import pandas as pd

names = ["Harry", "Larry", "Carry", "Narry"]
marks = [80, 60, 100, 90]
series = pd.Series(data=marks, index=names)


# Series Methods......
print(series.head()) # return Value from The Head of Series...
print(series.head(2)) # return the top elements of series...

print(series.tail()) # return Value from Bottom of series...
print(series.tail(3)) # return minimum value of series...

print(series.max()) # return maximum value of series...
print(series.min()) # return minimum value of series....
print(series.sum()) # return Sum of Series....
print(series.mean()) # return Average of Series...

print(series.sort_values(ascending=True)) # Sort the value by accending and decending order..
print(series.sort_values(ascending=False))
print(series.sort_index(ascending=True)) # Sorting by index......
print(series.sort_values(ascending=False))

# Series Attributes....
print(series.dtype) # Give Datatype of Series...
print(series.size) # Give Size of Series...
print(series.ndim) # Give Dimentions of Series...
print(series.nbytes) # Give Number of Bytes...
print(series.empty) # Return Boolean value true if series has no elements and return false if series has elements....
series0 = pd.Series(["Harry", "Larry", "Carry", None], index=[1, 2, 3, 4])
print(series0.hasnans) # Return True if series has none Value and false if series has No any none value...
print(series.index) # Give Index of series...
print(series.values) # Give Value of Series...


# Applying Conditions and Operations on Series.....
print(series[series>60]) # return value of series that are greater than 60.....
s1 = pd.Series([5, 10, 15, 20], ["A", "B", "C", "D"])
s2 = pd.Series([10, 20, 30, 40], ["A", "B", "C", "D"])
# index must be same in both s1 and s2 series to perform Operations, if index is not same then the operation will be performed only on upto same index left value of index will be return as none value./..
print(s1*s2)
print(s1/s2)
print(s1-s2)
print(s1+s2)
